#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import SlideTransition kivy.uix.screenmanager.SlideTransition
#:import Factory kivy.factory.Factory

#:set bg 'cartas/b3.jpg'

<Widget>:
    font_name:'Pirata_One/PirataOne-Regular'

<Manager>:
    transition: FadeTransition()
    Inicio:
        name:'inicio'
    Regras:
        name:'regras'
    Escolha:
        name:'escolha'
    Porta:
        name:'porta'
    Jogo:
        name:'jogo'
    Fim_de_jogo:        
        name:'vitoria'
    Morte:
        name:'derrota'

#{“x”:1, “y”:1, “left”:1, “right”:1, "center_x":1, "center_y":1, "top”:1, “bottom”:1}

<Inicio>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:'cartas/logo.png'
    Button:
        text:'Jogar'
        size_hint:.25, .10
        border:(0, 0, 0, 0)
        pos_hint:{"center_x":0.5, "center_y":0.1}
        background_normal:'cartas/botao1.png'
        background_down:'cartas/botao1.png'
        on_press: app.root.current = 'escolha'
    Button:
        text:'Regras'
        size_hint:.15, .10
        border:(0, 0, 0, 0)
        pos_hint:{"center_x":0.9, "center_y":0.1}
        background_normal:'cartas/botao1.png'
        background_down:'cartas/botao1.png'
        on_press: app.root.current = 'regras'
    Button:
        text:'Sair'
        size_hint:.15, .10
        border:(0, 0, 0, 0)
        pos_hint:{"center_x":0.1, "center_y":0.1}
        background_normal:'cartas/botao1.png'
        background_down:'cartas/botao1.png'
        on_press:app.stop()

<Pass_Reg@ButtonBehavior+Label>:
    size_hint:[0.07,1]
    font_size:100

<Regras>:
    Image:
        id:pag
        allow_stretch:True
        keep_ratio:False
        size:self.size
        pos:self.pos
        source:'cartas/regras/p1.jpg'
    Pass_Reg:
        text:'<'
        pos_hint: {'x': 0}
        on_press:root.voltar()
    Pass_Reg:
        text:'>'
        pos_hint: {'x': .93}
        on_press:root.passar()
    But_menu:

<Botao_num@Button>:
    font_size:0.2*(self.width+self.height)
    color:0,0,0,1
    size_hint:0.5,1
    border:0, 0, 0, 0
    background_normal:'cartas/personagens/numero.png'
    background_down:'cartas/personagens/numeroselec.png'

<But_menu@RelativeLayout>:
    Button:
        pos_hint: {'left': 1, 'top': 1}
        text:'inicio'
        border:(0, 0, 0, 0)
        size_hint:0.1,0.07
        background_normal:'cartas/botao1.png'
        background_down:'cartas/botao1.png'
        on_press:app.root.current = 'inicio'

<Escolha>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:bg
    But_menu:

    BoxLayout:
        orientation: 'vertical'
        spacing:30
        
        Image:
            source:'cartas/escolha1.png'
            size_hint_y: 0.35
            Label:
                text:'ESCOLHE TEU PERSONAGEM'
                color:0,0,0,1
                font_size:.02*(self.parent.width+self.parent.height)
                #size_hint_y: 0.2
                pos: self.parent.pos
                size: self.parent.size

        BoxLayout:
            padding:[10,0]
            spacing:10
            Button:       
                id:mago    
                border:(0, 0, 0, 0) 
                background_normal:'cartas/personagens/mago.png'
                background_down:'cartas/personagens/magoselec.png'
                on_press: root.troca('mago')
            Button:      
                id:exploradora      
                border:(0, 0, 0, 0)
                background_normal:'cartas/personagens/exploradora.png'
                background_down:'cartas/personagens/exploradoraselec.png'
                on_press: root.troca('exploradora')
            Button:  
                id:guerreiro    
                border:(0, 0, 0, 0)      
                background_normal:'cartas/personagens/guerreiro.png'
                background_down:'cartas/personagens/guerreiroselec.png'
                on_press: root.troca('guerreiro')
            Button: 
                id:ladra    
                border:(0, 0, 0, 0)       
                background_normal:'cartas/personagens/ladra.png'
                background_down:'cartas/personagens/ladraselec.png'
                on_press: root.troca('ladra')
            Button:   
                id:cavaleiro    
                border:(0, 0, 0, 0)     
                background_normal:'cartas/personagens/cavaleiro.png'
                background_down:'cartas/personagens/cavaleiroselec.png'
                on_press: root.troca('cavaleiro')
            Button:
                id:aleatorio
                border:(0, 0, 0, 0)
                background_normal:'cartas/personagens/aleatorio.png'
                background_down:'cartas/personagens/aleatorioselec.png'
                on_press: root.troca('aleatorio')
        BoxLayout:
            size_hint_y: 0.3
            #spacing:root.width/3
            padding:[20,0,20,20]
            BoxLayout:
                #size_hint_x:0.5
                orientation: 'vertical'
                padding:root.width/16, 0, root.width/3, 0   
                Label:
                    text:'QUANTOS JOGADORES TERÁ A PARTIDA?'
                    outline_width:1
                    font_size:.05*(self.width+self.height)
                BoxLayout:
                    spacing:root.width/15                          
                    Botao_num:
                        id:2
                        text:'2'
                        font_size:.25*(self.width+self.height)
                        on_press: root.trocabt(2)
                    Botao_num:
                        id:3
                        text:'3'
                        font_size:.25*(self.width+self.height)
                        on_press: root.trocabt(3)
                    Botao_num:
                        id:4
                        text:'4'
                        font_size:.25*(self.width+self.height)
                        on_press: root.trocabt(4)
                    Botao_num:
                        id:5
                        text:'5'
                        font_size:.25*(self.width+self.height)
                        on_press: root.trocabt(5)
            Button:
                size_hint:0.25,0.5
                text:'Seguir' 
                font_size:0.1*(self.width+self.height)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'
                on_press: root.seguir()
    Label:
        id:n_qjog
        text:'Escolhe a quantidade de jogadores'
        font_size:.03*(self.width+self.height)
        opacity:0
        pos_hint:{'y':.2}
    Label:
        id:n_jogs
        text:'Escolhe o teu Personagemm'
        font_size:.03*(self.width+self.height)
        opacity:0
        pos_hint:{'y':.3}

<Porta>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:'cartas/salas/porta.jpg'
    Label:
        id:porta_text
        size_hint:1, 0.2
        font_size:.02*(self.parent.width+self.parent.height)
        pos_hint:{"center_x":0.5, "center_y":0.93}

#mapa da sala         
<Mapa_da_sala@ButtonBehavior+BoxLayout>:
    size_hint:0.28,0.155
    pos_hint: {'right': 1, 'top': 1}
    pos:self.pos
<MapaPopup>:
    title_align:'center'
    title_font:'Pirata_One/PirataOne-Regular'
    title_size:0.02*(self.width+self.height)
    separator_height: 0
    size_hint:[0.7,0.5]
    BoxLayout:
        id:mapa_pop

<Jogo>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:bg
    But_menu:

    #conteudo da sala
    Image:
        id:imagem_conteudo_sala 
        size_hint:0.5, 0.5
        pos_hint:{"center_x":0.5, "center_y":0.6}
        source:
    
    #mapa da sala
    RelativeLayout:
        Mapa_da_sala:
            id:mapa_sala
            on_press:Factory.MapaPopup(self, root.m).open()

    BoxLayout:
        id:boxx
        size_hint_y:0.3
        orientation: 'vertical'        

        #botao seguir
        BoxLayout:
            size_hint_y:0.3
            padding:0.001*(self.width+self.height)
            Widget:
                size_hint_x:0.8
            Button:
                id:bt_seguir
                size_hint:0.2, 1
                text:'Seguir' 
                font_size:0.05*(self.width+self.height)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'

        #cartas do jogador   
        StackLayout:                
            id:cartas
            padding:[self.width/5,0,0,0]
            orientation:'lr-tb'

    #caso nenhuma carta seja escolhida
    Label:
        id:mensagem        
        opacity:0
        font_size:0.02*(self.width+self.height)
        pos_hint:{"center_x":0.5, "center_y":0.7}

    #resultado da luta contra um monstro
    Label:
        id:mensagem_monstro
        opacity:0
        font_size:0.02*(self.width+self.height)
        pos_hint:{"center_x":0.5, "center_y":0.9}
    StackLayout: 
        id:mensagem_monstro_dano
        opacity:0
        orientation:'tb-lr'
        padding:[self.width/6.5, self.height/10, 0, 0]
    StackLayout: 
        id:mensagem_chefe_dano
        opacity:0
        orientation:'tb-lr'
        padding:[self.width/4.5, self.height/10, 0, 0]

    #cartoes dos personagens
    StackLayout: 
        id:per_card
        orientation:'tb-lr'
        padding:[0,self.height/10,0,0]
    StackLayout: 
        id:per_coracao
        orientation:'tb-lr'
        padding:[self.width/13, self.height/10*1.4, 0, 0]
        spacing:self.height/12
    StackLayout: 
        id:per_saco
        orientation:'tb-lr'
        padding:[self.width/8.5, self.height/10*1.4, 0, 0]
        spacing:self.height/12
    StackLayout: 
        id:per_carta
        opacity:0
        orientation:'tb-lr'
        padding:[self.width/9, self.height/10, 0, 0]
    StackLayout: 
        id:per_carta2
        opacity:0
        orientation:'tb-lr'
        padding:[self.width/6, self.height/10, 0, 0]

<CartasDoJogador>:
    size_hint: 0.1, 1
    on_press:self.parent.parent.parent.cart_selec(self.id)
    border:(0, 0, 0, 0)

<VidaJogador>:
    background_normal:'cartas/personagens/coracao.png'
    background_down:'cartas/personagens/coracao.png'
    size_hint:[0.04,0.1]
    border:(0, 0, 0, 0)
    font_size:0.3*(self.width+self.height)

<DinheiroJogador>:
    background_normal:'cartas/personagens/saco.png'
    background_down:'cartas/personagens/saco.png'
    size_hint:[0.04,0.1]
    border:(0, 0, 0, 0)
    font_size:0.3*(self.width+self.height)

<CartaJogada>:
    size_hint:[0.035,0.15]

<ResultadoSala>:
    font_size:0.15*(self.width+self.height)
    size_hint:[0.15,0.15]


<Morte>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:bg
    BoxLayout:
        orientation:'vertical'
        size_hint:0.7,0.7
        pos_hint:{"center_x":0.5, "center_y":0.5}
        Label:
            text:'MORRESTE'
            font_size:0.09*(self.width+self.height)
        BoxLayout:
            size_hint_y:0.3
            Button:
                text:'Jogar novamente'
                font_size:0.04*(self.width+self.height)
                border:(0, 0, 0, 0)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'
                on_press:app.root.current='escolha'
            Button:
                text:'sair'
                font_size:0.04*(self.width+self.height)
                border:(0, 0, 0, 0)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'
                on_press:app.stop()

<Fim_de_jogo>:
    canvas:
        Rectangle:
            size:self.size
            pos:self.pos
            source:bg
    BoxLayout:
        orientation:'vertical'
        size_hint:0.7,0.7
        pos_hint:{"center_x":0.5, "center_y":0.5}
        Label:
            text:'FIM DE JOGO'
            font_size:0.09*(self.width+self.height)
        Label:
            id:ganha
            text:
            font_size:0.04*(self.width+self.height)
        Label:
            id:morre
            text:
            font_size:0.04*(self.width+self.height)
        BoxLayout:
            size_hint_y:0.3
            Button:
                text:'Jogar novamente'
                font_size:0.04*(self.width+self.height)
                border:(0, 0, 0, 0)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'
                on_press:app.root.current='escolha'
            Button:
                text:'Início'
                font_size:0.04*(self.width+self.height)
                border:(0, 0, 0, 0)
                background_normal:'cartas/botao1.png'
                background_down:'cartas/botao1.png'
                on_press:app.root.current='inicio'
    StackLayout: 
        id:per_card_fim
        orientation:'tb-lr'
        padding:[0,self.height/10,0,0]
    StackLayout: 
        id:per_coracao_fim
        orientation:'tb-lr'
        padding:[self.width/13, self.height/10*1.4, 0, 0]
        spacing:self.height/12
    StackLayout: 
        id:per_saco_fim
        orientation:'tb-lr'
        padding:[self.width/8.5, self.height/10*1.4, 0, 0]
        spacing:self.height/12
